### ISSUE TITLE
Constants prefixes

### ISSUE THREAD

**Issue by Alexey-T** [ad1mt/Multi-Word-Int#1]
```
type
	int8u		= byte;
	int8		= shortint;
	int16		= smallint;
	int16u		= word;
	int32		= longint;
	int32u		= longword;
	int64u		= QWord;
```
these names will clash with FPC's integer types. general idea: add e.g. `Multi` prefix to these names. and if so, other const-names (and type-names) also need the same prefix.

**Comment by ad1mt** [comment]
Resolved
