### ISSUE TITLE
Names casing

### ISSUE THREAD

**Issue by Alexey-T** [ad1mt/Multi-Word-Int#2]
`T_Leading_Zeros	=	(Keep_Leading_Zeros, Trim_Leading_Zeros);`

let us use Delphi style (Pascal style) for identifiers:

`TLeadingZeros = (lzKeepLeadingZeroes, lzTrimLeadingZeros);`

and here prefix `Multi` is also good: `TMultiLeadingZeros`.

**Comment by ad1mt** [comment]
Please see discussion on Free Pascal forum.

**Comment by benibela** [comment]
or you could try scoped enums
