### ISSUE TITLE
indents inside begin...end

### ISSUE THREAD

**Issue by Alexey-T** [ad1mt/Multi-Word-Int#6]
Each level of begin/end should have indent inside. by 2 spaces or by tab-char.
here is ending of your code

![Screenshot from 2023-12-14 09-15-38](https://github.com/ad1mt/Multi-Word-Int/assets/4154978/bc7562d2-0f23-4854-93de-905ab87a5c3f)

issues

- begin/end of function don't have indent insize
- begin/end of `if (Multi_XV_size < 1) then` too
- begin/end of `while (i <= Multi_X2_max) do` too

it looks bad and not like in 99.99% of other codes.

**Comment by Alexey-T** [comment]
Example again.

![Screenshot from 2023-12-14 09-17-58](https://github.com/ad1mt/Multi-Word-Int/assets/4154978/42b0f26f-aca9-4e45-81c2-99b2b55200ca)

this should be formatter like this:

![Screenshot from 2023-12-14 09-19-05](https://github.com/ad1mt/Multi-Word-Int/assets/4154978/d73f4aab-4da7-4ddb-8c18-0c467aaae6c8)

**Comment by ad1mt** [comment]
I implemented some of your suggestions, but not the ones regarding style of coding.
I started a discussion about this on the thread I created, here...
   https://forum.lazarus.freepascal.org/index.php/topic,65158.30.html
I would much rather have a discussion there.
